name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run script with trace warnings
        run: node --trace-warnings task-definition.js
